### ISSUE TITLE
Issue adding micrographs near edges of reference micrograph

### ISSUE THREAD

**Issue by hannahcunning** [StraboSpot/Strabo-Micro#15]
I am trying to add a micrograph of the edge of my thin section as a scaled rectangle using trace scale bar and drag. When I get close to the edge of the reference micrograph I am unable to move the new micrograph to the edge. I have attached a picture showing how close I am able to get it.  It seems like there is a barrier that is keeping the micrographs from the edge, as I am able to freely drag it around the middle of the reference image. 
![image](https://user-images.githubusercontent.com/54119012/129221690-c247c8ba-f7e1-4621-b171-ea1cb10c5d02.png)

**Comment by jasonash** [comment]
Hi Hannah. This sometimes happens when you trace the scale bar and then enter an incorrect value for the pixel conversion and the image gets suddenly blown up way larger than the reference micrograph. The coordinates get corrupted and the dragging code doesn't know where to place the associated micrograph. I know how to fix this, but it is going to take a lot of development time to get it fixed. In the meantime, you might try loading your associated micrograph again. If it still doesn't work, you might have to choose the "Stretch and Drag" option instead of tracing the scale bar. I will let you know when this is fixed so you can try it out.

**Comment by hannahcunning** [comment]
OK, I have saved them as associated point for now. Thanks!

**Comment by jasonash** [comment]
Issue has been improved. Will fix permanently with future release.
